### ISSUE TITLE
Hello from FastGit

### ISSUE THREAD

**Issue by KevinZonda** [jadezi/github-accelerator#2]
Hello, this is FastGit. Now we have the mirror booster service.   
Here is our mirror link -> <https://git.fastgit.org>.  
Would you like to add our services to your script? 
BTW, We also provide agents for GitHub release and so on.

Sorry to disturb you. Have a good day! :)

**Comment by jadezi** [comment]
Thank you for providing a new mirror URL, I will be happy to add him to my script
